import Head from "next/head";
import Image from "next/image";
import Contact from "./../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Buildit -website Buildit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className=" flex flex-col top-0 relative space-y-4 text-[#486A6F] text-clip  pt-14 px-20">
        <img
          src="./assets/Figure.svg"
          className="absolute h-full right-0 top-0"
          alt=""
        />
        <div className="flex">
          <div className="py-24">
            <h1 className="text-6xl font-bold  max-w-xl text-[#486A6F] ">
              Development company
            </h1>
            <p className="text-lg py-4">
              Forward-thinking real estate developer, owner <br /> and investor
              with a reputation
            </p>
            <div className=" text-white text-sm flex gap-4 items-center py-12">
              <button className="bg-[#486A6F] py-3 px-6 rounded-md">
                Service
              </button>
              <button className="bg-[#C6DBFF] py-3 px-8 text-[#486A6F] font-bold">
                About the company
              </button>
            </div>
          </div>
          <div className="relative z-10 p-10">
            <img src="./assets/Photos.png" alt="" />
          </div>
        </div>
      </header>

      <div className="flex flex-col gap-6 justify-center my-8 items-center p-20 text-[#486A6F]">
        <h1 className="font-bold text-3xl">Innovative Execution</h1>
        <div className="grid grid-cols-3 gap-6 max-w-3xl mx-auto py-12 ">
          <div>
            <img src="/assets/Icon.svg" alt="" />
            <div className="flex flex-col gap-2 py-4">
              <h1 className="font-bold text-lg">Featured Listing</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
          </div>
          <div>
            <img src="/assets/Icon.svg" alt="" />
            <div className="flex flex-col gap-2 py-4">
              <h1 className="font-bold text-lg">Available properties</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
          </div>
          <div>
            <img src="/assets/Icon.svg" alt="" />
            <div className="flex flex-col gap-2 py-4">
              <h1 className="font-bold text-lg">In the News</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
          </div>
        </div>
      </div>
      <div className="bg-[#E1EBFA] py-7 text-[#486A6F]">
        <div className="max-w-6xl mx-auto px-3 ">
          <img src="./assets/logos.png" alt="" />
        </div>
        <div className="max-w-5xl my-4 mx-auto px-3">
          <div className="grid grid-cols-2 gap-6">
            <div className="flex items-center justify-center">
              <img src="/assets/about.png" className="w-4/5" alt="" />
            </div>
            <div>
              <h4 className="text-sm  my-3">About</h4>
              <h4 className="text-xl font-bold  leading-[50px]">
                Owner and investor with a reputation
              </h4>
              <p className="text-sm my-5 leading-7 text-primary">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
                elit sem, vestibulum sed leo eu, malesuada pharetra mauris.
                Integer rhoncus, eros vel euismod tempor, ipsum magna tristique
                nisi, quis ullamcorper enim magna eu orci. Sed semper ex quis
                semper aliquet. Cras hendrerit molestie sapien sed fermentum.
                Mauris dui tortor, viverra vel ultrices in, congue sed ex.
              </p>
              <button className="bg-[#486A6F] py-3 px-8 rounded-md text-white">
                Explore
              </button>
            </div>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-5 my-20 max-w-5xl mx-auto px-3">
        <div className="text-[#486A6F]">
          <h4 className="text-sm text-[#5BCCDE] my-3">Available Properties</h4>
          <h4 className="text-2xl font-bold text-primaryDark leading-[50px]">
            Featured Listing
          </h4>
          <p className="text-sm my-5 leading-7 text-primary">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elit
            sem, vestibulum sed leo eu, malesuada pharetra mauris. Integer
            rhoncus, eros vel euismod tempor, ipsum magna tristique nisi, quis
            ullamcorper enim magna eu orci. Sed semper ex quis semper aliquet.
            Cras hendrerit molestie sapien sed fermentum. Mauris dui tortor,
            viverra vel ultrices in, congue sed ex.
          </p>
          <button className="bg-[#486A6F] py-3 px-8 rounded-md text-white">
            Explore
          </button>
        </div>
        <div>
          <img src="/assets/Photos.png" alt="" />
        </div>
      </div>
      <div className="bg-[#E1EBFA] flex flex-col gap-2 justify-center items-center pt-24">
        <p className="text-[#5BCCDE]">Socials</p>
        <h1 className="text-[#486A6F] text-3xl font-bold">On instagram</h1>
        <div className="max-w-5xl mx-aut p-14">
          <div className="grid grid-cols-3 gap-6">
            <img src="/assets/card.png" alt="" />
            <img src="/assets/card1.png" alt="" />
            <img src="/assets/card2.png" alt="" />
            <img src="/assets/card3.png" alt="" />
            <img src="/assets/card4.png" alt="" />
            <img src="/assets/card5.png" alt="" />
          </div>
        </div>
      </div>
      <Contact />
    </div>
  );
}
